config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
	root 'app#index'

	resources :app, only: [:index]

	resources :users, only: [] do
		collection do
			get :papers
		end
	end
	
	resources :events do
		member do
			get :evaluators
			get :papers
			get :share
			post :apply_evaluator
		end
	end

	resources :papers do
		member do
			get :apply_evaluator
			get :ratings
			get :evaluate
			post :apply_evaluation
		end
	end

	resources :event_users, only: [] do 
		member do
			get :accept
			get :refuse
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :user_type
  has_many :papers
  has_many :ratings
  has_many :events

	has_many :event_users
  has_many :teacher_events, through: :event_users, source: :event  
end

app/models/user_type.rb
class UserType < ApplicationRecord
	has_many :users

  enum kind: {owner: 'owner', teacher: 'teacher'}

  def pt_kind
  	owner? ? "Instituição" : "Professor"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :destroy, :update, :apply_evaluator, :ratings]

	def index
	end

	def new
		@user = User.new(event_id: params[:event_id])
	end

	def create
		@user = User.new(user_params)
		@user.save
	end

	def edit
	end

	def update
		@user.update_attributes(user_params)
	end

	def destroy
		@user.destroy
	end

	def papers
		@papers = current_user.papers.includes(:students, :event).order(title: :asc).paginate(:page => params[:page], :per_page => 10)
	end

	private
	def set_user
		@user = User.find_by_id(params[:id])
	end

  def user_params
    params.require(:user).permit(:name, :email, :password, :user_type_id)
  end

end

app/views/users/_teacher_event_user.html.erb
<tr>
	<td><%= event_user.user.name %></td>
	<td><%= event_user.user.email %></td>
	<td>
		<div class="input-group">
      <div class="input-group-btn">
		    <button data-toggle="dropdown" type="button" class="btn btn-white dropdown-toggle">
		    	<%= get_status_string event_user.status %>
		    	<i class="caret"></i>
		    </button>
	      <ul class="dropdown-menu">
        	<li>
	        	<%= link_to "Aceitar", accept_event_user_path(event_user) %>
        	</li>
        	<li>
	        	<%= link_to "Recusar", refuse_event_user_path(event_user) %>
        	</li>
	      </ul>
	    </div>
		</div>	
	</td>
</tr>

app/views/users/_teacher_paper.html.erb
<tr>
	<td><%= format_date paper.event.start_at %></td>
	<td><%= paper.title %></td>
	<td><%= truncate(paper.students_name_formatted, length: 30) %></td>
	<td><%= link_to "Visualizar", paper.content, target: :new, class: "btn btn-light" %></td>
	<td><%= link_to "Avaliar", evaluate_paper_path(paper), class: "btn btn-light" %>
	</td>
</tr>

app/views/users/papers.html.erb
<section class="dashboard-counts no-padding-bottom no-padding-top">

  <div class="row no-padding">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Data</th>
                <th>Título</th>
                <th>Alunos</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "teacher_paper", collection: @papers, as: :paper %>
            </tbody>
          </table>

          <%= will_paginate(@papers, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

        </div>
      </div>
    </div>
  </div>
</section>