config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
	root 'app#index'

	resources :app, only: [:index]

	resources :users, only: [] do
		collection do
			get :papers
		end
	end
	
	resources :events do
		member do
			get :evaluators
			get :papers
			get :share
			post :apply_evaluator
		end
	end

	resources :papers do
		member do
			get :apply_evaluator
			get :ratings
			get :evaluate
			post :apply_evaluation
		end
	end

	resources :event_users, only: [] do 
		member do
			get :accept
			get :refuse
		end
	end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
 	
 	has_many :papers
  has_many :event_users
  has_many :teachers_event_users, -> { joins(:user).where(users: {user_type_id: UserType.teacher.first.id}) }, class_name: 'EventUser'

  has_one  :token

  has_many :criteria

  has_many :students, -> { where(user_type_id: UserType.student.first.id) }, through: :event_users, source: :user
  has_many :teachers, -> { where(user_type_id: UserType.teacher.first.id) }, through: :event_users, source: :user

  after_create :generate_token

  def valid_token? token
    self.token.key == token && self.token.active?
  end

  def bind_dates start_at, end_at, accept_until
    self.start_at             = DateTime.strptime(start_at, '%d/%m/%Y') if !start_at.blank?
    self.end_at               = DateTime.strptime(end_at, '%d/%m/%Y') if !start_at.blank?
    self.accept_papers_until  = DateTime.strptime(accept_papers_until, '%d/%m/%Y') if !start_at.blank?
  end

  private
  def generate_token
  	key = SecureRandom.base64(10).tr('+/=lIO0', 'pqrsxyz')
  	Token.create(key: key, event: self)
  end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	
	before_action :set_event, only: [:edit, :destroy, :update, :evaluators, :papers, :share, :apply_evaluator]
	before_action :check_token, only: [:share]

	def index
		@events = current_user.events.paginate(:page => params[:page], :per_page => 10)

		@events = @events.includes(:token).order(start_at: :desc)
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		@event.bind_dates(params[:event][:start_at], params[:event][:end_at], params[:event][:accept_papers_until])
		@event.user = current_user

		criteria = create_criteria

		@event.save
		@event.criteria << criteria


		redirect_to events_path
	end

	def edit
	end

	def update
		@event.update_attributes(event_params)
		@event.criteria << update_criteria

		redirect_to events_path
	end

	def destroy
		@event.destroy

		redirect_to events_path
	end

	def evaluators
		@teachers_event_users = @event.teachers_event_users.includes(:user).order("users.name")
	end

	def papers
		@papers = @event.papers.includes(:students).order(title: :asc)
	end

	def share
		@paper = Paper.new(event: @event)

	end

	def apply_evaluator
		if !current_user.user_type.teacher? || @event.teachers.exists?(current_user.id)
			redirect_to "/"
			return
		end

		@event.teachers << current_user
		redirect_to "/"
	end

	private
	def set_event
		@event = Event.find_by_id(params[:id])
	end

  def event_params
    params.require(:event).permit(:title, :place, :description, :start_at, :end_at, :accept_papers_until, :user)
  end

  def check_token
  	@valid_token = @event.valid_token?(params[:token]) 
  end


  def create_criteria
  	return [] if params[:criteria].nil?

  	criteria = []

  	params[:criteria].each do |criterium_param|
  		next if criterium_param[:remove]
  		criteria << Criterium.create(name: criterium_param[:name])
  	end

  	criteria
  end

  def update_criteria
  	return [] if params[:criteria].nil?

		newest_criteria = []
  	params[:criteria].each do |criterium_param|

  		if !criterium_param[:id].blank? && criterium_param[:remove]
  			Criterium.find(criterium_param[:id]).destroy
  		elsif !criterium_param[:id].blank?
  			Criterium.find(criterium_param[:id]).update_attributes(name: criterium_param[:name])
  		elsif !criterium_param[:remove]
				newest_criteria << Criterium.create(name: criterium_param[:name])
  		end

  	end

		newest_criteria
  end
	
end

app/views/events/_apply_evaluator.html.erb
<%= form_tag(apply_evaluator_event_path(event), :html => { :role => "form", method: :post }) do |f| %>
 
	<div class="checks">
		<%= check_box_tag :agree, false, {class: "checkbox-template", id: "checkboxAgree"} %>
	  <label for="checkboxAgree">Aceito ser avaliador do evento</label>
	</div>

	<div class="row no-padding">
		<div class="col-lg-10"></div>
		<div class="col-lg-2">
	    <%= submit_tag "Confirmar", :class=>"btn btn-info" %>
		</div>
	</div>
  
<% end %>

app/views/events/_event.html.erb
<tr>
	<td><%= event.title %></td>
	<td><%= event.place %></td>
	<td><%= format_date event.start_at %></td>
	<td>
    <div class="input-group">
      <div class="input-group-btn">
		    <button data-toggle="dropdown" type="button" class="btn btn-white dropdown-toggle">
		    	Opções<i class="caret"></i>
		    </button>
	      <ul class="dropdown-menu">
	        <li>
	        	<%= link_to "Editar", edit_event_path(event) %>
	        </li>
	        <li>
	        	<%= link_to "Remover", event, method: :delete, data: { confirm: "Tem certeza?" } %>
        	</li>
        	<li>
	        	<%= link_to "Compartilhar", "#", { "data-toggle" => "modal", "data-target" => "#myModal", "onclick" => "populateModal('#{event.id}', '#{event.token.key}')" }%>
        	</li>
      	 	<li>
	        	<%= link_to "Avaliadores", evaluators_event_path(event) %>
        	</li>
      		<li>
	        	<%= link_to "Trabalhos", papers_event_path(event) %>
        	</li>
	      </ul>
	    </div>
		</div>	
	</td>
</tr>

app/views/events/_form.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center">
    <h3 class="h4"> <%= @event.new_record? ? "Criando" : "Editando" %> evento</h3>
  </div>
  <div class="card-body">    
    <div class="row">
      <div class="col-lg-6">

        <%= form_for(@event, :html => { :role => "form" }) do |f| %>
          <% if @event.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <h2>Os seguintes errors foram encontrados:</h2>

              <ul>
              <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <label class="form-control-label">Título</label>
            <%= f.text_field :title, :class => "form-control", :maxlength => 150 %> 
          </div>

           <div class="form-group">
            <label class="form-control-label">Descrição</label>
            <%= f.text_area :description, rows: 10, :class => "form-control" %> 
          </div>

           <div class="form-group">
            <label class="form-control-label">Local</label>
            <%= f.text_field :place, :class => "form-control", :maxlength => 200 %> 
          </div>

          <div class="form-group">
            <label class="form-control-label">Início</label>
            <%= f.text_field :start_at, :class => "form-control datepicker", "data-provide" => :datepicker, "data-date-format" => "yyyy/mm/dd", value: (format_date @event.start_at) %> 
          </div>

          <div class="form-group">
            <label class="form-control-label">Término</label>
            <%= f.text_field :end_at, :class => "form-control datepicker", "data-provide" => :datepicker, "data-date-format" => "yyyy/mm/dd", value: (format_date @event.end_at)  %> 
          </div>

          <div class="form-group">
            <label class="form-control-label">Aceite de avaliadores</label>
            <%= f.text_field :accept_papers_until, :class => "form-control datepicker", "data-provide" => :datepicker, "data-date-format" => "yyyy/mm/dd", value: (format_date @event.accept_papers_until) %> 
          </div>

          <div class="row">
            <div class="col-lg-10">  
              <br/>  
              <h2 class="field">Critérios de avalição</h2>

              <div id="fields-criteria">
                <br>
                <% @event.criteria.each do |criterium| %>
                  <div id="fieldset-quantity-criterium-<%= criterium.id %>">
                    <fieldset class="form-inline">
                      <input type="text" hidden="true" name=criteria[][id] value=<%= criterium.id %>>

                      <div class="row">
                        <div class="col-lg-10">
                          <input type="text" class="form-control form-control-sm" name=criteria[][name] placeholder="Nome" value="<%= criterium.name %>">
                        </div>
                     
                        <div class="col-lg-2">
                          <button id="criterium-<%= criterium.id %>" type="button" onclick="removeCriteriumFields('<%= criterium.id %>')" class="btn btn-info btn-sm remove-criterium">Remover</button>
                          <input type="checkbox" id="criterium_remove_checkbox_<%= criterium.id %>" class="form-control form-control-sm" name=criteria[][remove] hidden>
                        </div>
                     
                      </div>
                     
                    </fieldset>
                    <br>
                  </div>
                <% end %>

              </div>

              <button id="add-criterium" type="button" class="btn btn-info btn-sm" onclick="addCriterium()">Adicionar</button>
              <br/>
              <br/>
            </div>
          </div>
         

          <div class="actions">
            <%= link_to "Cancelar", events_path, :class=>"btn btn-info" %></a>
            <%= f.submit "Salvar", :class=>"btn btn-info" %>
          </div>

        <% end %>
      </div>
    </div>
    
  </div>
</div>

<script>
    $('.datepicker').datepicker({
      format: 'dd/mm/yyyy',
      language: 'pt-BR',
      weekStart: 0
    });
</script>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/evaluators.html.erb
<div class="breadcrumb-holder container-fluid">
  <ul class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Eventos", events_path %></li>
    <li class="breadcrumb-item"><%= @event.title %></li>
    <li class="breadcrumb-item active">Avaliadores</li>
  </ul>
</div>

<section class="dashboard-counts no-padding-bottom no-padding-top">
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <table class="table table-sm">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Email</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              <%= render partial: "users/teacher_event_user", collection: @teachers_event_users, as: :event_user %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<section class="dashboard-counts no-padding-bottom no-padding-top">
  <%= link_to "Criar evento", new_event_path, class: "btn btn-success", id: "add-button" %>

  <div class="row no-padding">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <table class="table table-sm ">
            <thead>
              <tr>
                <th>Título</th>
                <th>Lugar</th>
                <th>Data</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= render @events %>
            </tbody>
          </table>

          <div class="row">
            <div class="col-lg-12">
              <%= will_paginate(@posts, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>



<%= render 'partials/modal' %>

<script type="text/javascript">
  
  function populateModal(eventId, eventToken) {
    var modalTitle = "Compartilhar evento";
    var modalMessage = "Compartilhe o link abaixo para que os avaliadores possam se cadastrar no evento";
    var teacherMessage = "Link para avaliadores:"

    var urlTeacher = window.location.protocol + "//" + window.location.hostname + ":" +window.location.port + "/events/" + eventId + "/share?token=" + eventToken;

    var content = "<p>" + modalMessage + "</p>"
                  + "<p><strong>" + teacherMessage + "</strong></p>"
                  + "<p><a href='" + urlTeacher + "'>" + urlTeacher + "</a></p>";

    var headerModal = $("#headerModal");
    var contentModal = $("#contentModal");
    var actionsModal = $("#actionsModal");

    headerModal.html(modalTitle);
    contentModal.html(content);

  }
</script>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/papers.html.erb
<div class="breadcrumb-holder container-fluid">
  <ul class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Eventos", events_path %></li>
    <li class="breadcrumb-item"><%= @event.title %></li>
    <li class="breadcrumb-item active">Trabalhos</li>
  </ul>
</div>

<section class="dashboard-counts no-padding-bottom no-padding-top">
  <%= link_to "Registrar trabalho", new_paper_path(event_id: @event.id), class: "btn btn-success", id: "add-button" %>

  <div class="row no-padding">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <table class="table table-sm">
            <thead>
              <tr>
                <th>Título</th>
                <th>Alunos</th>
                <th>Avaliador</th>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <%= render @papers %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>

<%= render 'partials/modal' %>

<script type="text/javascript">
  
  var tableAvaliators = '<table class="table">\
                                    <thead>\
                                      <tr>\
                                        <th class="col-lg-10">Nome</th>\
                                        <th class="col-lg-2"></th>\
                                      </tr>\
                                    </thead>\
                                    <tbody>\
                                      <% if @papers.size > 0 %>\
                                        <% @papers.first.event.teachers_event_users.includes(:user).each do |event_user| %>\
                                          <% next if !event_user.accepted? %>\
                                          <tr>\
                                            <td><%= event_user.user.name %></td>\
                                            <td>\
                                              <%= link_to "Selecionar", "#", class: "btn btn-light", onclick: "applyEvaluator(#{event_user.user.id})" %>\
                                            </td>\
                                          </tr>\
                                        <% end %>\
                                      <% end %>\
                                    </tbody>\
                                  </table>';

  var modalTitle = "Selecione um avaliador";

  var headerModal = $("#headerModal");
  var contentModal = $("#contentModal");
  var actionsModal = $("#actionsModal");

  var paperSelectedId = 0;

  headerModal.html(modalTitle);
  contentModal.html(tableAvaliators);

  function onPaperSelected(paperId) {
    paperSelectedId = paperId;
  }

  function applyEvaluator(evaluatorId) {
    var url = "/papers/" + paperSelectedId + "/apply_evaluator?user_id=" + evaluatorId;
    $.get(url, function(data) {
      location.reload();
    });
  }

</script>

app/views/events/share.html.erb
<section class="dashboard-counts no-padding-bottom">

  <div class="row no-padding">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
            <p><strong>Título:</strong> <%= @event.title %></p>
            <p><strong>Descrição:</strong> <%= @event.description %></p>
            <p><strong>Início:</strong> <%= format_date @event.start_at %> <strong>Término:</strong> <%= format_date @event.end_at %></p>
            <p><strong>Limite de submissão de trabalhos:</strong> <%= format_date @event.accept_papers_until %></p>

            <%= @valid_token ? (render 'apply_evaluator', event: @event) : (render 'papers/form', event: @paper) %>
        </div>
      </div>
    </div>
  </div>
</section>