config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => "registrations"}
	root 'app#index'

	resources :app, only: [:index]

	resources :users, only: [] do
		collection do
			get :papers
		end
	end
	
	resources :events do
		member do
			get :evaluators
			get :papers
			get :share
			post :apply_evaluator
		end
	end

	resources :papers do
		member do
			get :apply_evaluator
			get :ratings
			get :evaluate
			post :apply_evaluation
		end
	end

	resources :event_users, only: [] do 
		member do
			get :accept
			get :refuse
		end
	end
end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :event
	has_and_belongs_to_many :students
  has_many :ratings
  belongs_to :user, optional: true

	def self.upload file
		cloudnary_file = Cloudinary::Uploader.upload(file)
    cloudnary_file["secure_url"].present? ? cloudnary_file["secure_url"] : ""
	end

	def students_name_formatted
		students.map(&:name).map{ |name| name.partition(" ").first }.join(", ")
	end


	def has_rating_consideration?
		ratings.map(&:considerations).each {|consideration| return true if !consideration.blank?}

		false
	end
end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
	before_action :set_paper, only: [:edit, :destroy, :update, :apply_evaluator, :ratings, :evaluate, :apply_evaluation]

	def index
		@papers = Paper.all
	end

	def new
		@paper = Paper.new(event_id: params[:event_id])
	end

	def create
		@paper = Paper.new(paper_params)
		@paper.content = Paper.upload(params[:paper][:content]) if params[:paper][:content].present?

		students = create_students

		@paper.save
		@paper.students << students

		redirect_to papers_event_path(@paper.event)
	end

	def edit
	end

	def update
		@paper.update_attributes(paper_params)
		@paper.students << update_students

		redirect_to papers_event_path(@paper.event)
	end

	def destroy
		@paper.destroy

		redirect_to papers_path
	end

	def apply_evaluator
		@evaluator = User.find_by_id(params[:user_id])
		@paper.update_attributes(user: @evaluator) if @evaluator.user_type.teacher?

		redirect_to papers_event_path(@paper.event)
	end

	def ratings
		@ratings = @paper.ratings.includes(:criterium)
	end

	def evaluate
	end

	def apply_evaluation
		@paper.ratings.destroy_all

		params[:ratings].each do |rating| 
			Rating.create(criterium_id: rating[:id], value: rating[:value], user_id: params[:evaluator_id], paper: @paper, considerations: rating[:considerations])
		end

		redirect_to papers_users_path
	end


	private
	def set_paper
		@paper = Paper.find_by_id(params[:id])
	end

  def paper_params
    params.require(:paper).permit(:title, :description, :event_id, :user)
  end

  def create_students
  	students = []

  	params[:students].each do |student_param|
  		next if student_param[:remove]
  		students << Student.create(name: student_param[:name])
  	end

  	students
  end

  def update_students
		newest_students = []
  	params[:students].each do |student_param|

  		if !student_param[:id].blank? && student_param[:remove]
  			Student.find(student_param[:id]).destroy
  		elsif !student_param[:id].blank?
  			Student.find(student_param[:id]).update_attributes(name: student_param[:name])
  		elsif !student_param[:remove]
				newest_students << Student.create(name: student_param[:name])
  		end

  	end

		newest_students
  end
	
end

app/views/papers/_form.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center">
    <h3 class="h4"> <%= @paper.new_record? ? "Registrando" : "Editando" %> trabalho</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-lg-6">

        <%= form_for(@paper, :html => { :role => "form" }) do |f| %>
          <% if @paper.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <h2>Os seguintes errors foram encontrados:</h2>

              <ul>
              <% @paper.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <%= f.hidden_field :event_id %> 

          <div class="form-group">
            <label class="form-control-label">Título</label>
            <%= f.text_field :title, :class => "form-control", :maxlength => 150 %> 
          </div>

          <div class="form-group">
            <label class="form-control-label">Descrição</label>
            <%= f.text_area :description, rows: 10, :class => "form-control" %> 
          </div>

          <div class="form-group">
            <label class="form-control-label">Anexo</label>
            <%= f.file_field :content %> 
          </div>

          <div class="row">
            <div class="col-lg-10">  
              <br/>  
              <h2 class="field">Alunos</h2>

              <div id="fields-students">
                <br>
                <% @paper.students.each do |student| %>
                  <div id="fieldset-quantity-student-<%= student.id %>">
                    <fieldset class="form-inline">
                      <input type="text" hidden="true" name=students[][id] value=<%= student.id %>>

                      <div class="row">
                        <div class="col-lg-10">
                          <input type="text" class="form-control form-control-sm" name=students[][name] placeholder="Nome" value=<%= student.name %>>
                        </div>
                     
                        <div class="col-lg-2">
                          <button id="student-<%= student.id %>" type="button" onclick="removeStudentFields('<%= student.id %>')" class="btn btn-info btn-sm remove-student">Remover</button>
                          <input type="checkbox" id="student_remove_checkbox_<%= student.id %>" class="form-control form-control-sm" name=students[][remove] hidden>
                        </div>
                     
                      </div>
                     
                    </fieldset>
                    <br>
                  </div>
                <% end %>

              </div>
            

              <button id="add-student" type="button" class="btn btn-info btn-sm" onclick="addStudent()">Adicionar</button>
              <br/><br/>
            </div>
          </div>

          <div class="actions">
            <%= link_to "Cancelar", papers_event_path(@paper.event), :class=>"btn btn-info" %></a>
            <%= f.submit "Salvar", :class=>"btn btn-info" %>
          </div>

        <% end %>
      </div>
    </div>
    
  </div>
</div>

app/views/papers/_paper.html.erb
<tr>
	<td><%= paper.title %></td>
	<td><%= truncate(paper.students_name_formatted, length: 30) %></td>
	<td>
		<button class="btn btn-light" data-toggle="modal", data-target="#myModal", onclick="onPaperSelected(<%= paper.id %>)"><%= paper.user.present? ? paper.user.name : "Adicionar" %></button>
	</td>
	<td><%= link_to "Visualizar", paper.content, target: :new %></td>
	<td>
		<div class="input-group">
      <div class="input-group-btn">
		    <button data-toggle="dropdown" type="button" class="btn btn-white dropdown-toggle">
		    	Opções
		    	<i class="caret"></i>
		    </button>
	      <ul class="dropdown-menu">
        	<li>
	        	<%= link_to "Editar", edit_paper_path(paper) %>
	        </li>
	        <li>
	        	<%= link_to "Remover", paper, method: :delete, data: { confirm: "Tem certeza?" } %>
        	</li>
	        <li>
	        	<%= link_to "Notas", ratings_paper_path(paper) %>
        	</li>
	      </ul>
	    </div>
		</div>	
	</td>
</tr>

app/views/papers/edit.html.erb
<%= render 'form' %>

app/views/papers/evaluate.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center">
    <h3 class="h4"> Avaliando</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-lg-12">

      	<%= form_tag(apply_evaluation_paper_path(@paper), :html => { :role => "form", method: :post }) do |f| %>
 					
      		<input type="text" name="evaluator_id" value="<%= current_user.id %>" hidden="true">

    			<% ratings = @paper.ratings %>

      		<% @paper.event.criteria.each do |criterium| %>
						<% rate = ratings.select {|rate_inner| rate_inner.criterium_id == criterium.id }.first %>

						<fieldset>
              <input type="text" name=ratings[][id] hidden="true" value=<%= criterium.id %>>
  						<%= criterium.name %>

              <div class="row">
                <div class="col-lg-4">
	                  <input type="number" step="0.1" max="10" class="form-control form-control-sm" name=ratings[][value] placeholder="Nota" value="<%= rate.value if rate.present? %>">

                </div>
              </div>

              <br/>
              <div class="row">
                <div class="col-lg-4">
                  <textarea class="form-control" name=ratings[][considerations] placeholder="Considerações"><%= rate.considerations if rate.present? %></textarea>
                </div>
              </div>


             
             	<br/>
            </fieldset>

					<% end %>

					<div class="actions">
            <%= link_to "Cancelar", papers_users_path, :class=>"btn btn-info" %>
      	    <%= submit_tag "Confirmar", :class=>"btn btn-info" %>
          </div>					
				  
				<% end %>

      </div>
    </div>
    
  </div>
</div>

app/views/papers/new.html.erb
<%= render 'form' %>

app/views/papers/ratings.html.erb
<div class="breadcrumb-holder container-fluid">
  <ul class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Eventos", events_path %></li>
    <li class="breadcrumb-item"><%= @paper.event.title %></li>
    <li class="breadcrumb-item"><%= link_to "Trabalhos", papers_event_path(@paper.event) %></li>
    <li class="breadcrumb-item"><%= @paper.title %></li>
    <li class="breadcrumb-item active">Notas</li>
  </ul>
</div>

<section class="dashboard-counts no-padding-bottom no-padding-top">

  <div class="row no-padding">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-body">
          <table class="table table-sm">
            <thead>
              <tr>
                <th class="col-lg-10">Critério</th>
                <th class="col-lg-2">Nota</th>
              </tr>
            </thead>
            <tbody>
              <%= render @ratings %>
            </tbody>
          </table>


          <% if @paper.has_rating_consideration? %>
            <div>
              <h4>Considerações</h4>

              <% @paper.ratings.includes(:criterium).each do |rating| %>
                <% if !rating.considerations.blank? %>
                  <p><%= rating.criterium.name %>: <%= rating.considerations %></p>
                <% end %>
              <% end %>
            </div>
          <% end %>
          
        </div>


      </div>
    </div>
  </div>

 
</section>